apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Release.Name }}-kafka-cluster
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV1
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}