// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Message struct {
	ID   string `json:"id"`
	Body string `json:"body"`
}

func (Message) IsNode()            {}
func (this Message) GetID() string { return this.ID }

type MessageConnection struct {
	Edges      []*MessageEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount *int32         `json:"totalCount,omitempty"`
}

type MessageEdge struct {
	Node   *Message `json:"node"`
	Cursor string   `json:"cursor"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RoomEdge struct {
	Node   *Room  `json:"node"`
	Cursor string `json:"cursor"`
}

type RoomMember struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (RoomMember) IsNode()            {}
func (this RoomMember) GetID() string { return this.ID }

type RoomMemberConnection struct {
	Edges      []*RoomMemberEdge `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount *int32            `json:"totalCount,omitempty"`
}

type RoomMemberEdge struct {
	Node   *RoomMember `json:"node"`
	Cursor string      `json:"cursor"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }
