package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/sudame/chat/internal/consts"
	"github.com/sudame/chat/internal/read_api/model"
)

type Message struct {
	PK        string `dynamodbav:"PK"` // ROOM#<id>
	SK        string `dynamodbav:"SK"` // MESSAGE#<id>
	MessageID string `dynamodbav:"message_id"`
	Body      string `dynamodbav:"body"`
	RoomID    string `dynamodbav:"room_id"`
	UserID    string `dynamodbav:"user_id"`
}

// Messages is the resolver for the messages field.
func (r *roomResolver) Messages(ctx context.Context, obj *model.Room, first *int32, after *string, last *int32, before *string) (*model.MessageConnection, error) {
	// first と before が同時に指定されている
	if first != nil && before != nil {
		return nil, fmt.Errorf("invalid input: first and before")
	}
	// last と after が同時に指定されている
	if last != nil && after != nil {
		return nil, fmt.Errorf("invalid input: last and after")
	}

	// first と last が同時に指定されている
	if first != nil && last != nil {
		return nil, fmt.Errorf("invalid input: first and last")
	}

	// first も last も指定されていない
	if first == nil && last == nil {
		return nil, fmt.Errorf("invalid input: no first and no last")
	}

	params := QueryParams{
		PK:       "ROOM#" + obj.ID,
		SKPrefix: new("MESSAGE#"),
		First:    first,
		After:    after,
		Last:     last,
		Before:   before,
	}

	var con *Connection[Message]

	if first != nil {
		p := params.ToQueryForwardParams()
		var err error
		con, err = QueryForward[Message](ctx, r.DynamoDBClient, consts.DynamoDBTableName, p)
		if err != nil {
			return nil, fmt.Errorf("failed to query forward: %w", err)
		}
	} else {
		p := params.ToQueryBackwardParams()
		var err error
		con, err = QueryBackward[Message](ctx, r.DynamoDBClient, consts.DynamoDBTableName, p)
		if err != nil {
			return nil, fmt.Errorf("failed to query backward: %w", err)
		}
	}

	var edges = []*model.MessageEdge{}
	for _, item := range con.Items {
		if item == nil || item.Node == nil {
			continue
		}
		edge := model.MessageEdge{
			Node: &model.Message{
				ID:   item.Node.MessageID,
				Body: item.Node.Body,
			},
			Cursor: item.Cursor,
		}
		edges = append(edges, &edge)
	}

	messageConnection := model.MessageConnection{
		Edges:    edges,
		PageInfo: con.PageInfo,
	}

	return &messageConnection, nil
}
