package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/sudame/chat/internal/consts"
	"github.com/sudame/chat/internal/read_api/graph"
	"github.com/sudame/chat/internal/read_api/model"
)

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.RoomConnection, error) {
	result, err := r.DynamoDBClient.Query(ctx, &dynamodb.QueryInput{
		TableName:                 new(consts.DynamoDBUserTableName),
		AttributesToGet:           nil,
		ConditionalOperator:       "",
		ConsistentRead:            new(false),
		ExclusiveStartKey:         nil,
		ExpressionAttributeNames:  nil,
		ExpressionAttributeValues: nil,
		FilterExpression:          nil,
		IndexName:                 nil,
		KeyConditionExpression:    nil,
		KeyConditions:             nil,
		Limit:                     nil,
		ProjectionExpression:      nil,
		QueryFilter:               nil,
		ReturnConsumedCapacity:    "",
		ScanIndexForward:          new(bool),
		Select:                    "",
	})
	if err != nil {
		return nil, fmt.Errorf("failed to query: %w", err)
	}
	panic("")
}

// TotalCount is the resolver for the totalCount field.
func (r *roomConnectionResolver) TotalCount(ctx context.Context, obj *model.RoomConnection) (*int32, error) {
	panic(fmt.Errorf("not implemented: TotalCount - totalCount"))
}

// RoomConnection returns graph.RoomConnectionResolver implementation.
func (r *Resolver) RoomConnection() graph.RoomConnectionResolver { return &roomConnectionResolver{r} }

type roomConnectionResolver struct{ *Resolver }
