package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/sudame/chat/internal/consts"
	"github.com/sudame/chat/internal/read_api/graph"
	"github.com/sudame/chat/internal/read_api/middleware"
	"github.com/sudame/chat/internal/read_api/model"
)

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.RoomConnection, error) {
	// first と before が同時に指定されている
	if first != nil && before != nil {
		return nil, fmt.Errorf("invalid input: first and before")
	}
	// last と after が同時に指定されている
	if last != nil && after != nil {
		return nil, fmt.Errorf("invalid input: last and after")
	}

	// first と last が同時に指定されている
	if first != nil && last != nil {
		return nil, fmt.Errorf("invalid input: first and last")
	}

	// first も last も指定されていない
	if first == nil && last == nil {
		return nil, fmt.Errorf("invalid input: no first and no last")
	}

	userID, err := middleware.GetUserID(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID: %w", err)
	}

	params := QueryParams{
		PK:     "USER#" + userID,
		First:  first,
		After:  after,
		Last:   last,
		Before: before,
	}

	var con *Connection[JoinedRoom]

	if first != nil {
		p := params.ToQueryForwardParams()
		con, err = QueryForward[JoinedRoom](ctx, r.DynamoDBClient, consts.DynamoDBTableName, p)
		if err != nil {
			return nil, fmt.Errorf("failed to query foward: %w", err)
		}
	} else {
		p := params.ToQueryBackwardParams()
		con, err = QueryBackward[JoinedRoom](ctx, r.DynamoDBClient, consts.DynamoDBTableName, p)
		if err != nil {
			return nil, fmt.Errorf("failed to query backward: %w", err)
		}
	}

	edges := make([]*model.RoomEdge, len(con.Items))
	for i, item := range con.Items {
		if item == nil || item.Node == nil {
			continue
		}
		edge := model.RoomEdge{
			Node: &model.Room{
				ID:   item.Node.RoomID,
				Name: "Not Implemented", // TODO: implement this
			},
			Cursor: item.Cursor,
		}
		edges[i] = &edge
	}

	roomConnection := model.RoomConnection{
		Edges:    edges,
		PageInfo: con.PageInfo,
	}

	return &roomConnection, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *roomConnectionResolver) TotalCount(ctx context.Context, obj *model.RoomConnection) (*int32, error) {
	panic(fmt.Errorf("not implemented: TotalCount - totalCount"))
}

// RoomConnection returns graph.RoomConnectionResolver implementation.
func (r *Resolver) RoomConnection() graph.RoomConnectionResolver { return &roomConnectionResolver{r} }

type roomConnectionResolver struct{ *Resolver }
