
CREATE TABLE IF NOT EXISTS chat_room_members (
  id CHAR(255) PRIMARY KEY,
  user_id CHAR(255) NOT NULL,
  chat_room_id CHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
