name: write-server

replicaCount: 1

image:
  # skaffold で設定している
  # repository:
  # tag:
  pullPolicy: Never

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
