// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_room.sql

package db

import (
	"context"
	"database/sql"
)

const createChatRoom = `-- name: CreateChatRoom :execresult
INSERT INTO chat_rooms (id, name) VALUES (?, ?)
`

type CreateChatRoomParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChatRoom, arg.ID, arg.Name)
}

const getChatRoom = `-- name: GetChatRoom :one
SELECT id, name, created_at, updated_at FROM chat_rooms WHERE id = ? LIMIT 1
`

func (q *Queries) GetChatRoom(ctx context.Context, id string) (ChatRoom, error) {
	row := q.db.QueryRowContext(ctx, getChatRoom, id)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
