// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertEvent = `-- name: InsertEvent :execresult
INSERT INTO event_records (id, event_type, payload) VALUES (?, ?, ?)
`

type InsertEventParams struct {
	ID        string          `json:"id"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEvent, arg.ID, arg.EventType, arg.Payload)
}
