// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"
	"database/sql"
)

const createMember = `-- name: CreateMember :execresult
INSERT INTO chat_room_members (id, user_id, chat_room_id) VALUES (?, ?, ?)
`

type CreateMemberParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	ChatRoomID string `json:"chat_room_id"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMember, arg.ID, arg.UserID, arg.ChatRoomID)
}

const getMember = `-- name: GetMember :one
SELECT id, user_id, chat_room_id, created_at, updated_at FROM chat_room_members WHERE id = ? LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id string) (ChatRoomMember, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i ChatRoomMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatRoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByChatRoomAndUser = `-- name: GetMemberByChatRoomAndUser :one
SELECT id, user_id, chat_room_id, created_at, updated_at FROM chat_room_members WHERE chat_room_id = ? AND user_id = ? LIMIT 1
`

type GetMemberByChatRoomAndUserParams struct {
	ChatRoomID string `json:"chat_room_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetMemberByChatRoomAndUser(ctx context.Context, arg GetMemberByChatRoomAndUserParams) (ChatRoomMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByChatRoomAndUser, arg.ChatRoomID, arg.UserID)
	var i ChatRoomMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatRoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembersByChatRoomID = `-- name: GetMembersByChatRoomID :many
SELECT id, user_id, chat_room_id, created_at, updated_at FROM chat_room_members WHERE chat_room_id = ?
`

func (q *Queries) GetMembersByChatRoomID(ctx context.Context, chatRoomID string) ([]ChatRoomMember, error) {
	rows, err := q.db.QueryContext(ctx, getMembersByChatRoomID, chatRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatRoomMember
	for rows.Next() {
		var i ChatRoomMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatRoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
