// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"
	"database/sql"
)

const getMessage = `-- name: GetMessage :one
SELECT id, user_id, chat_room_id, body, created_at, updated_at FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatRoomID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postMessage = `-- name: PostMessage :execresult
INSERT INTO messages (id, user_id, chat_room_id, body) VALUES (?, ?, ?, ?)
`

type PostMessageParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	ChatRoomID string `json:"chat_room_id"`
	Body       string `json:"body"`
}

func (q *Queries) PostMessage(ctx context.Context, arg PostMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, postMessage,
		arg.ID,
		arg.UserID,
		arg.ChatRoomID,
		arg.Body,
	)
}
