// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (sql.Result, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetChatRoom(ctx context.Context, id string) (ChatRoom, error)
	GetMember(ctx context.Context, id string) (ChatRoomMember, error)
	GetMemberByChatRoomAndUser(ctx context.Context, arg GetMemberByChatRoomAndUserParams) (ChatRoomMember, error)
	GetMembersByChatRoomID(ctx context.Context, chatRoomID string) ([]ChatRoomMember, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetUser(ctx context.Context, id string) (User, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (sql.Result, error)
	PostMessage(ctx context.Context, arg PostMessageParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
